"""add dividend table

Revision ID: a7ab2f6a51dc
Revises: be363b75e11b
Create Date: 2026-07-16 11:46:21.508418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7ab2f6a51dc'
down_revision: Union[str, None] = 'be363b75e11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('amount_per_share', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('write_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'ex_date', name='unique_stock_ex_date')
    )
    op.create_index(op.f('ix_dividend_ex_date'), 'dividend', ['ex_date'], unique=False)
    op.create_index(op.f('ix_dividend_stock_id'), 'dividend', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_stock_id'), table_name='dividend')
    op.drop_index(op.f('ix_dividend_ex_date'), table_name='dividend')
    op.drop_table('dividend')
    # ### end Alembic commands ###
